### ISSUE TITLE
对toast组件增加"class-name=xxx"的类不起作用

### ISSUE THREAD

**Issue by Wmengxi** [linrui1994/mpvue-toast#1]
改变toast的样式，按照说明使用“class-name”增加类，但是不起作用，求解决方法，感谢！

**Comment by steinslin** [comment]
@Wmengxi  我这边测试是正常的，能给下你的代码吗

**Comment by Wmengxi** [comment]
@linrui1994 感谢回复 但这个问题已经解决啦 这个issue可以关闭啦
